SQL :
  addr : 1.1.1.1
  port : 3306
  user : learn  # 数据库账号
  pass : 123456 # 数据库密码
  database : learning_path # 数据库名称
  maxIdle: 20 # 空闲连接池数量
  maxOpen: 100 # 最大连接数
  maxLife: 30 # 连接后空闲状态维持时间(秒)


Redis:
  addr : 1.1.1.1:6379  # redis地址和端口
  password : "myredis1234"
  db : 2 # 数据库编号
  dialTimeout : 3 # 连接超时时间(秒)